class ActionTypeEnum:
    STANDARIZE_CHANNELS = 1
    DECOMPOSE_SINGLE_CHANNEL_RESOLUTION = 2
    REVERSE_DECOMPOSE_SINGLE_CHANNEL_RESOLUTION = 3
    DESTANDARIZE_CHANNEL = 4 #BY NAME
    CONVERT_CHANNEL = 5

    DECOMPOSE_WHOLE_IMAGE_CHANNELS = 6
    REVERSE_DECOMPOSE_WHOLE_IMAGE_CHANNELS = 7

    DISPLAY_IMAGE = 8